name: 'Issue assigner'

on:
  issues:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: patrickhulce/issue-assigner@master
        with:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          maintainers: 'patrickhulce,paulirish'
